######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 18 15:17:59 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += drawer.h tga.h
SOURCES += drawer.cpp pbtest.cpp qt4-test.cpp tga.cpp
